models_encoders:
  n: [20, 20]
  w: 40
  n_buckets: 13000
  p_padding: 10
  seed: 69

models_params:
  seed: 69

  anomaly_likelihood:
    probationaryPeriod: 500
    reestimationPeriod: 100

  sp:
    potentialPct: 0.8
    columnDimensions: [64, 32]
    potentialRadius: 16
    localAreaDensity: 0.02
    numActiveColumnsPerInhArea: 0
    globalInhibition: true
    boostStrength: 0.
    stimulusThreshold: 0
    synPermConnected: 0.2
    synPermActiveInc: 0.003
    synPermInactiveDec: 0.0005
    wrapAround: no
    minPctOverlapDutyCycle: 0.001
    dutyCyclePeriod: 1000

  tm:
    cellsPerColumn: 2
    activationThreshold: 20
    initialPerm: 0.21
    maxSegmentsPerCell: 32
    maxSynapsesPerSegment: 64
    minThreshold: 13
    newSynapseCount: 31
    permanenceInc: 0.2
    permanenceDec: 0.002
    permanenceConnected: 0.5
    predictedSegmentDecrement: 0.008  # (roughly 2 * permInc * sparsity)


models_predictor:
  enable: no
  resolution: 1
  sdrc_alpha: 0.1
  steps_ahead:
  - 1
  - 2


spatial_anomaly:
  enable: no
  tolerance: 0.05
  perc_min: 0
  perc_max: 100
  anom_prop: 0.3
  window: 100000
