features:
  x:
    type: float
    weight: 1.0
    min:
    max:
    resolution:
  y:
    type: float
    weight: 1.0
    min:
    max:
    resolution:

models_state:
  model_for_each_feature: true
  return_pred_count: no
  use_sp: true

timesteps_stop:
  learning:
  running:
  sampling:
